/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package homework;

import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.GridLayout;
import java.awt.event.ItemEvent;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *
 * @author Amr
 */
public class InsertOnTable extends javax.swing.JFrame {

    /**
     * Creates new form InsertOrUpdateOnTable
     */
    public InsertOnTable() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ComboBoxTableName = new javax.swing.JComboBox<>();
        logLabel = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();
        insertBtn = new javax.swing.JButton();
        resetBtn = new javax.swing.JButton();
        columnsPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ComboBoxTableName.setBackground(new java.awt.Color(0, 0, 0));
        ComboBoxTableName.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Table To View", "ProductionLines", "Employees", "MedicationCategory", "Medications", "Cities", "Distributors", "Orders", "OrderItems", "Invoices", "InvoiceItems" }));
        ComboBoxTableName.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ComboBoxTableNameItemStateChanged(evt);
            }
        });
        ComboBoxTableName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxTableNameActionPerformed(evt);
            }
        });

        logLabel.setBackground(new java.awt.Color(204, 204, 204));
        logLabel.setFont(new java.awt.Font("Eras Medium ITC", 0, 14)); // NOI18N
        logLabel.setForeground(new java.awt.Color(204, 204, 204));
        logLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        logLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        logLabel.setEnabled(false);
        logLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        logLabel.setOpaque(true);

        backBtn.setBackground(java.awt.SystemColor.activeCaption);
        backBtn.setFont(new java.awt.Font("Eras Medium ITC", 0, 14)); // NOI18N
        backBtn.setForeground(new java.awt.Color(0, 0, 0));
        backBtn.setText("Back");
        backBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        insertBtn.setBackground(java.awt.SystemColor.activeCaption);
        insertBtn.setFont(new java.awt.Font("Eras Medium ITC", 0, 14)); // NOI18N
        insertBtn.setForeground(new java.awt.Color(0, 0, 0));
        insertBtn.setText("Insert");
        insertBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        insertBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertBtnActionPerformed(evt);
            }
        });

        resetBtn.setBackground(java.awt.SystemColor.activeCaption);
        resetBtn.setFont(new java.awt.Font("Eras Medium ITC", 0, 14)); // NOI18N
        resetBtn.setForeground(new java.awt.Color(0, 0, 0));
        resetBtn.setText("Reset");
        resetBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        resetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetBtnActionPerformed(evt);
            }
        });

        columnsPanel.setBackground(new java.awt.Color(204, 204, 204));
        columnsPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        javax.swing.GroupLayout columnsPanelLayout = new javax.swing.GroupLayout(columnsPanel);
        columnsPanel.setLayout(columnsPanelLayout);
        columnsPanelLayout.setHorizontalGroup(
            columnsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        columnsPanelLayout.setVerticalGroup(
            columnsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 55, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(266, 266, 266)
                        .addComponent(ComboBoxTableName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(237, 237, 237)
                        .addComponent(insertBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67)
                        .addComponent(resetBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(258, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(columnsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(logLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 524, Short.MAX_VALUE))
                .addGap(86, 86, 86))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(ComboBoxTableName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(columnsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(insertBtn)
                    .addComponent(resetBtn))
                .addGap(18, 18, 18)
                .addComponent(logLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                .addGap(27, 27, 27)
                .addComponent(backBtn)
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ComboBoxTableNameItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ComboBoxTableNameItemStateChanged
        // TODO add your handling code here:               
        if(evt.getStateChange() == ItemEvent.SELECTED){
            String selectedTable = ComboBoxTableName.getSelectedItem().toString();                        
            if(selectedTable.equals("Select Table To View"))
            {         
                columnsPanel.removeAll(); // Clear the components from the panel
                columnsPanel.revalidate();
                columnsPanel.repaint();
                return;
            }         
            
             columnsPanel.removeAll(); // Clear the components from the panel
             columnsPanel.setLayout(new GridLayout());

             
             ArrayList<String> columnsName = DataBaseHelper.getColumnsNames(selectedTable);
             for(int i=1;i<columnsName.size();i++)
             {
                 JTextField colTextField = new JTextField(columnsName.get(i));
                 colTextField.setBackground(Color.GRAY);
                 colTextField.setForeground(Color.BLACK);
                 columnsPanel.add(colTextField);
             }

             columnsPanel.revalidate();
             columnsPanel.repaint();
        }        
    }//GEN-LAST:event_ComboBoxTableNameItemStateChanged

    private void ComboBoxTableNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxTableNameActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_ComboBoxTableNameActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        
        dispose();
        
        MainPage mPage = new MainPage();
        
        mPage.show();
        
    }//GEN-LAST:event_backBtnActionPerformed

    private void insertBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertBtnActionPerformed
        // TODO add your handling code here:
        String selectedTable = ComboBoxTableName.getSelectedItem().toString();                        
        ArrayList<String> row= new ArrayList<String>();
                
        for (Component c : columnsPanel.getComponents()) {
            if (c instanceof JTextField) {
                row.add(((JTextField) c).getText());                
            }
        }
        
        if(DataBaseHelper.validateInput(selectedTable, row)){
            DataBaseHelper.insert(selectedTable, row);
        }
    }//GEN-LAST:event_insertBtnActionPerformed

    private void resetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetBtnActionPerformed
        // TODO add your handling code here:
        
        String selectedTable = ComboBoxTableName.getSelectedItem().toString();                        
        
        ArrayList<String> columnsName = DataBaseHelper.getColumnsNames(selectedTable);
        int index=1;
        for (Component c : columnsPanel.getComponents()) {
            if (c instanceof JTextField) {
                ((JTextField) c).setText(columnsName.get(index));
                index++;
            }
        }
    }//GEN-LAST:event_resetBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InsertOnTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InsertOnTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InsertOnTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InsertOnTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InsertOnTable().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboBoxTableName;
    private javax.swing.JButton backBtn;
    private javax.swing.JPanel columnsPanel;
    private javax.swing.JButton insertBtn;
    private javax.swing.JLabel logLabel;
    private javax.swing.JButton resetBtn;
    // End of variables declaration//GEN-END:variables
}
