/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package homework;

/**
 *
 * @author Amr
 */
public class MainPage extends javax.swing.JFrame {

    /**
     * Creates new form MainPage
     */
    public MainPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        viewTableBtn = new javax.swing.JButton();
        insertBtn = new javax.swing.JButton();
        createViewBtn = new javax.swing.JButton();
        createTriggerBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(50, 50));
        setPreferredSize(new java.awt.Dimension(800, 600));

        jPanel2.setBackground(java.awt.Color.lightGray);
        jPanel2.setAlignmentX(0.0F);
        jPanel2.setAlignmentY(0.0F);
        jPanel2.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        jPanel2.setMinimumSize(new java.awt.Dimension(0, 0));
        jPanel2.setPreferredSize(new java.awt.Dimension(600, 800));

        viewTableBtn.setBackground(java.awt.SystemColor.activeCaption);
        viewTableBtn.setFont(new java.awt.Font("Eras Medium ITC", 0, 14)); // NOI18N
        viewTableBtn.setForeground(new java.awt.Color(0, 0, 0));
        viewTableBtn.setText("View Table");
        viewTableBtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 3, 3, 3));
        viewTableBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        viewTableBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        viewTableBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewTableBtnActionPerformed(evt);
            }
        });

        insertBtn.setBackground(java.awt.SystemColor.activeCaption);
        insertBtn.setFont(new java.awt.Font("Eras Medium ITC", 0, 14)); // NOI18N
        insertBtn.setForeground(new java.awt.Color(0, 0, 0));
        insertBtn.setText("Insert On Table");
        insertBtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 3, 3, 3));
        insertBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        insertBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        insertBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertBtnActionPerformed(evt);
            }
        });

        createViewBtn.setBackground(java.awt.SystemColor.activeCaption);
        createViewBtn.setFont(new java.awt.Font("Eras Medium ITC", 0, 14)); // NOI18N
        createViewBtn.setForeground(new java.awt.Color(0, 0, 0));
        createViewBtn.setText("Create View");
        createViewBtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 3, 3, 3));
        createViewBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        createViewBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        createViewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createViewBtnActionPerformed(evt);
            }
        });

        createTriggerBtn.setBackground(java.awt.SystemColor.activeCaption);
        createTriggerBtn.setFont(new java.awt.Font("Eras Medium ITC", 0, 14)); // NOI18N
        createTriggerBtn.setForeground(new java.awt.Color(0, 0, 0));
        createTriggerBtn.setText("Create Trigger");
        createTriggerBtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 3, 3, 3));
        createTriggerBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        createTriggerBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        createTriggerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createTriggerBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(viewTableBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(createViewBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(createTriggerBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(insertBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE))
                .addGap(96, 96, 96))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewTableBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(insertBtn))
                .addGap(39, 39, 39)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createViewBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(createTriggerBtn))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {createTriggerBtn, createViewBtn, insertBtn, viewTableBtn});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 689, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                .addGap(100, 100, 100))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void createTriggerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createTriggerBtnActionPerformed
        // TODO add your handling code here:
        
        DataBaseHelper.createTrigger();
        
    }//GEN-LAST:event_createTriggerBtnActionPerformed

    private void createViewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createViewBtnActionPerformed
        // TODO add your handling code here:
        DataBaseHelper.createView();
        dispose();
        createViewPage cvp = new createViewPage();
        
        cvp.show();
    }//GEN-LAST:event_createViewBtnActionPerformed

    private void insertBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertBtnActionPerformed
        // TODO add your handling code here:        
        dispose();
        InsertOnTable iotPage = new InsertOnTable();
        iotPage.show();        
    }//GEN-LAST:event_insertBtnActionPerformed

    private void viewTableBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewTableBtnActionPerformed
        // TODO add your handling code here:
        dispose();
        ViewTablePage vtPage = new ViewTablePage();

        vtPage.setVisible(true);        
    }//GEN-LAST:event_viewTableBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createTriggerBtn;
    private javax.swing.JButton createViewBtn;
    private javax.swing.JButton insertBtn;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton viewTableBtn;
    // End of variables declaration//GEN-END:variables
}
